events:
    - schedule: rate(2 hours)

websites:      
    - 搬瓦工:
        url: https://bwh88.net/cart.php?a=add&pid=72
        xpath: //div[@id='order-web20cart']//h1
        original: Oops, there's a problem...
    
    - AkkoCloud:
        url: https://www.akkocloud.com/cart.php?a=add&pid=13
        xpath: //div[@class='header-lined']//h1
        original: 缺货
        
    - Canon EF 50mm f/1.4 USM Lens:
        url: https://www.bhphotovideo.com/c/product/12140-USA/Canon_2515A003_50mm_f_1_4_USM_Autofocus.html
        xpath: //div[@data-selenium='pricingPrice']
        original: $399.00
        
    - Sigma 35mm f/1.4 DG HSM Art Lens for Canon EF:
        url: https://www.bhphotovideo.com/c/product/898831-REG/Sigma_340_101_35mm_f_1_4_DG_HSM.html
        xpath: //div[@data-selenium='pricingPrice']
        original: $799.00
    
    - Canon EF 16-35mm f/2.8L III USM Lens:
        url: https://www.bhphotovideo.com/c/product/1274708-REG/canon_ef_16_35mm_f_2_8l_iii.html
        xpath: //div[@data-selenium='pricingPrice']
        original: $2,199.00
        
    - MIXED-MATERIAL WRAP DRESS:
        url: https://www.toryburch.com/mixed-material-wrap-dress/57281.html?color=001&size=XXS
        xpath: //div[@data-id='ProductInformation']//div[@data-id='PriceContainer']//span
        original: $598
