events:
    - schedule: rate(2 hours)

websites:      
    - 搬瓦工:
        url: https://bwh88.net/cart.php?a=add&pid=72
        xpath: //div[@id='order-web20cart']//h1
        original: Oops, there's a problem...
